### ISSUE TITLE
Partial Dependencies shows only vertical line for certain cases

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#143]
For example, using the run `SMAC3v2/mlp-nondeterministic/run_1` with hyperparameter n_layer, only this is shown:

![newplot (30)](https://github.com/automl/DeepCAVE/assets/30651149/56e5e657-6c0a-4ca1-a932-c97d7e928916)

**Comment by helegraf** [comment]
I was already ready to give up with this but I finally found the cause of the bug:

PDP plots work exactly in the case that all the hyperparameters in the original ConfigSpace are sorted in an alphabetical order. Why? Because the PDP library copies the ConfigSpace with its own utility function, which gives the Hyperparameters new IDs, thus varying the wrong Hyperparameter, and DeepCAVE of course uses the IDs from the original ConfigSpace.

We should then probably create a bug report in the PDP repo but intermediate a fix on our side should be possible.

**Comment by sarah-segel** [comment]
Closed as it is a duplicate of https://github.com/automl/DeepCAVE/issues/111
